name: Format Check

on: [push, pull_request]

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or any other version you prefer

    - name: Install Prettier
      run: npm install --save-dev prettier

    - name: Check TypeScript and React formatting
      run: |
        npx prettier --check '**/*.ts'
        npx prettier --check '**/*.tsx'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # or any other version you prefer

    - name: Install Black
      run: pip install black

    - name: Check Python formatting
      run: black --check .

    - name: Temporarily Disable Microsoft Repo
      run: |
        sudo sed -i 's/deb/#deb/g' /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check C++ formatting
      run: |
        clang-format --version
        find . \( -path './GomokuEngine/external' -prune \) -o -name 'pybinds.cpp' -prune -o -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -i -style=file {} + && git diff --exit-code

