name: GomokuEngine tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup CMake
      uses: cmake/setup-cmake@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev python3-dev

    - name: Build and test
      working-directory: GomokuEngine
      run: |
        make test

    - name: Check test results
      if: ${{ failure() }}
      run: echo "Tests failed"

    - name: Mark commit status
      if: ${{ success() }}
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.git.createCommitStatus({
            context: 'GomokuEngine',
            state: 'success',
            description: 'All tests passed successfully'
          })
